### ISSUE TITLE
How can I send the same email to multiple people in one api call?

### ISSUE THREAD

**Issue by mantrala** [sendwithus/sendwithus_ruby#68]
This seems like it should be straightforward but I couldn't find it anywhere else.

Something like this for sendgrid:

[https://stackoverflow.com/questions/18612421/send-mail-for-multiple-user-and-the-each-recipents-have-only-his-email-address-n](url)

**Comment by FlipCodes** [comment]
Hi @mantrala,

The Sendwithus API only provides support for one recipient in the "to" field. Depending on what you're trying to do, you may be able to accomplish this using the CC or BCC fields (https://github.com/sendwithus/sendwithus_ruby#send_email-arguments). 

Note: we recommend sending emails to individual recipients where possible. This is because email events such as opens and clicks will be counted back to the primary recipient.

**Comment by mantrala** [comment]
@FlipCodes thank you for replying so fast. You can close the issue.

**Comment by FlipCodes** [comment]
You bet! :) 
Cheers @mantrala
